### ISSUE TITLE
Create sample apps

### ISSUE THREAD

**Issue by JohnClema** [evgenyneu/SigmaSwiftStatistics#3]
This could be a good way to exemplify Sigma's functions

**Comment by evgenyneu** [comment]
Hi, thank you for the suggestion. I considered creating a demo app but
decided that the unit tests would be enough. After all, this library is
just a collections of functions that take one or two parameters. I agree, a
demo app may be nice to have but I feel it can be an overkill in our case.
Also, the demo app can make it harder to expand and maintain the library in
the future. Maybe there are very good reasons for having a demo app that I
am missing, it is open for discussion.
