### ISSUE TITLE
Adding quantiles calculation & returning arrays

### ISSUE THREAD

**Issue by drinkius** [evgenyneu/SigmaSwiftStatistics#5]
I'm wondering if its a good idea to add quantiles calculation to your library. I'm currently in need of a tool which would return an array, say, of all the elements that are in the first 80% of the population. We'd need to calculate the quantile first and then run the selection algorithm on the initial array. I wonder if this functionality fits your library's philosophy, I'd be glad to contribute.

**Comment by evgenyneu** [comment]
Hi, @drinkius, very good idea! I have added the [percentile1](https://github.com/evgenyneu/SigmaSwiftStatistics#percentile-1) method. Here is how you can get the elements in the first 80% of the dataset:

```Swift
let dataset: [Double] = [1, 2, 3, 4, 5]
let percentileValue = Sigma.percentile1(values: dataset, percentile: 0.8)
// percentileValue: 4.2
let elementsInLeftPercentile = dataset.filter{ $0 <= percentileValue }
// elementsInLeftPercentile: [1, 2, 3, 4]
```

Let me know if it is what you wanted.

**Comment by evgenyneu** [comment]
The reason it is named percentile1, is because I am planning to add other methods corresponding to PERCENTILE.EXC in Excel and the one used in MATLAB.

**Comment by drinkius** [comment]
Thanks a lot, it's very useful!
